[workspace]
resolver = "2"

members = [
  "lab1",
  "lab2",
  "lab3",
  "lab4",
  "lab5",
  "lab6",
]

[workspace.dependencies]
rand = { version = "0.8.4" }
once_cell = { version = "1.18.0" }
criterion = { version = "0.5.1" }
thiserror = { version = "1.0.49" }
mpi = { version = "0.7.0" }
